export const categories = ['Nasional', 'Ekonomi', 'Teknologi', 'Kesehatan', 'Olahraga', 'Internasional'];
export type Article = { slug: string; title: string; excerpt: string; category: string; publishedAt: string; readTime: string; body: string[]; sources: { name: string; url: string }[] };
const baseBody = [
  'Perkembangan ini menjadi perhatian karena dampaknya dapat dirasakan oleh masyarakat, pelaku usaha, dan pembuat kebijakan. Informasi yang tersedia terus diperbarui seiring adanya keterangan resmi dan data pendukung dari berbagai pihak. Dalam liputan seperti ini, perubahan kecil pada angka, waktu, atau cakupan kebijakan dapat mengubah kesimpulan secara berarti. Karena itu, ringkasan ini tidak memperlakukan unggahan media sosial sebagai bukti tunggal dan tidak menyimpulkan hal yang belum dikonfirmasi. Pembaca dapat menggunakan tautan sumber di bagian akhir untuk memeriksa dokumen atau laporan yang menjadi rujukan.',
  'Pembaca perlu membedakan antara fakta yang telah dikonfirmasi, pernyataan narasumber, dan analisis. Redaksi menyusun konteks agar pembahasan lebih mudah dipahami tanpa menggantikan laporan asli dari sumber rujukan. Informasi faktual diutamakan bila berasal dari institusi yang berwenang atau dari beberapa laporan independen yang saling menguatkan. Bila terdapat perbedaan penjelasan, perbedaan itu perlu disebutkan secara terbuka, bukan disederhanakan agar sesuai dengan satu narasi. Pendekatan tersebut membantu pembaca menilai tingkat kepastian suatu informasi sebelum membagikannya kepada orang lain.',
  'Konteks historis juga penting. Peristiwa atau kebijakan biasanya tidak muncul tanpa latar belakang, melainkan dipengaruhi kondisi sebelumnya, target yang ingin dicapai, dan keterbatasan pelaksanaan. Menjelaskan konteks mencegah pembaca mengambil kesimpulan hanya berdasarkan satu kutipan atau potongan data. Pada saat yang sama, konteks tidak boleh dipakai untuk menutupi dampak yang benar-benar dialami kelompok tertentu. Suara warga, tenaga profesional, dan pelaksana di lapangan dapat memberi gambaran yang lebih lengkap ketika dipadukan dengan data yang dapat diperiksa.',
  'Dalam beberapa waktu ke depan, perkembangan lanjutan akan menentukan arah kebijakan dan respons publik. Hal yang layak dipantau mencakup pengumuman resmi, perubahan jadwal, penjelasan metodologi data, serta langkah perlindungan bagi pihak yang terdampak. Kami menyarankan pembaca memeriksa pengumuman institusi terkait untuk mendapatkan informasi paling mutakhir. Tanggal publikasi dan pembaruan juga perlu diperhatikan karena informasi yang benar pada satu waktu dapat menjadi tidak lengkap ketika fakta baru tersedia. Redaksi akan menandai perubahan substansial bila artikel ini diperbarui.',
  'Analisis dan konteks: isu ini memperlihatkan pentingnya keputusan berbasis data, komunikasi yang jelas, serta pengawasan publik. Dampaknya tidak berdiri sendiri; ia berkaitan dengan kondisi ekonomi, akses layanan, dan kepercayaan masyarakat. Pengambil keputusan perlu menerangkan tujuan, ukuran keberhasilan, dan cara mengurangi risiko yang mungkin muncul. Transparansi seperti itu memungkinkan publik membandingkan janji dengan hasil, sekaligus memberi masukan yang lebih spesifik. Bagi pembaca, pertanyaan sederhana dapat membantu: siapa yang menyediakan data, bagaimana data dikumpulkan, kelompok mana yang belum terwakili, dan apa yang masih belum diketahui?',
  'Nilai tambah dari pembahasan ini adalah ajakan untuk melihat konsekuensi praktis, bukan hanya judul utama. Rumah tangga mungkin mempertimbangkan biaya, waktu, dan akses informasi. Pelaku usaha dapat menilai kepastian aturan dan kebutuhan penyesuaian. Pemerintah daerah serta organisasi masyarakat bisa mengidentifikasi hambatan layanan yang tidak selalu tampak dalam data agregat. Menghubungkan beragam perspektif tidak berarti semua klaim mempunyai bobot yang sama; bukti yang kuat tetap harus diutamakan. Namun, perspektif tersebut membantu menemukan pertanyaan lanjutan yang relevan dan menghindari kesimpulan yang terlalu cepat.',
  'Sudut pandang yang lebih luas diperlukan agar pembaca tidak hanya melihat peristiwa hari ini. Membandingkan pengalaman daerah dan kelompok terdampak membantu mengidentifikasi peluang perbaikan dan risiko yang harus diantisipasi. Pembaca juga dapat mencari laporan primer, statistik resmi, dan penjelasan pakar dengan keahlian yang relevan sebelum membuat keputusan penting. Artikel ini merupakan ringkasan editorial independen, bukan pengganti sumber asli atau nasihat profesional. Jika tersedia fakta baru yang relevan, redaksi akan memperbarui konteks, atribusi, dan kesimpulan dengan jelas.'
];
export const articles: Article[] = [
  { slug: 'memahami-perkembangan-hari-ini', title: 'Memahami Perkembangan Hari Ini Melalui Fakta dan Konteks', excerpt: 'Ringkasan editorial yang menempatkan perkembangan terkini dalam konteks yang mudah dipahami.', category: 'Nasional', publishedAt: '24 Juli 2026', readTime: '5 menit', body: baseBody, sources: [{ name: 'Badan Pusat Statistik', url: 'https://www.bps.go.id/' }, { name: 'ANTARA', url: 'https://www.antaranews.com/' }, { name: 'Kementerian Komunikasi dan Digital', url: 'https://www.komdigi.go.id/' }] },
  { slug: 'teknologi-dan-layanan-publik', title: 'Teknologi dan Layanan Publik: Hal yang Perlu Diperhatikan', excerpt: 'Tinjauan singkat mengenai penggunaan teknologi dengan fokus pada manfaat publik dan akuntabilitas.', category: 'Teknologi', publishedAt: '24 Juli 2026', readTime: '4 menit', body: baseBody, sources: [{ name: 'Komdigi', url: 'https://www.komdigi.go.id/' }, { name: 'BRIN', url: 'https://www.brin.go.id/' }, { name: 'BPS', url: 'https://www.bps.go.id/' }] },
  { slug: 'ekonomi-rumah-tangga-dan-informasi', title: 'Ekonomi Rumah Tangga dan Pentingnya Informasi Terverifikasi', excerpt: 'Konteks ekonomi yang membantu pembaca menilai informasi dan dampaknya pada kehidupan sehari-hari.', category: 'Ekonomi', publishedAt: '23 Juli 2026', readTime: '5 menit', body: baseBody, sources: [{ name: 'Bank Indonesia', url: 'https://www.bi.go.id/' }, { name: 'BPS', url: 'https://www.bps.go.id/' }, { name: 'Kementerian Keuangan', url: 'https://www.kemenkeu.go.id/' }] }
];
export const getArticle = (slug: string) => articles.find((article) => article.slug === slug);
